### ISSUE TITLE
Milestone - 1

### ISSUE THREAD

**Issue by akanshaVashisth** [UBC-MDS/survey_arrival_time#3]
- [x] - Add Code of Conduct

- [x] - Add CONTRIBUTING.md file

- [x] - Read UBC Office of Research Ethics document on Using Online Surveys.

- [x] - Identify the question that your team in interested in answering with the survey. The aim of the survey should be to try to answer one specific and testable question. Examples of specific and testable questions include (you can use one of these if you really like them):

- [x] - Identify the other questions you plan to ask in your survey to identify confounding variables and justify/explain why you plan to include them.

- [x] - Describe how you plan to analyze the survey results (e.g., what statistical test(s) do you plan to employ?).

- [x] - Discuss the aspects of the UBC Office of Research Ethics document on Using Online Surveys that are relevant to your proposed survey.
